name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuración de Node.js (en este ejemplo usamos Node 18)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Instalación de dependencias y construcción de la aplicación
      - name: Install dependencies and Build
        run: |
          npm ci
          npm run build

      # 4. Despliegue en Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_GRASS_0E3A4630F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Token para integraciones con GitHub (e.g. comentarios en PR)
          action: "upload"
          app_location: "/"      # Ruta donde se encuentra el código fuente de tu app
          output_location: "dist"  # Ruta del folder generado por tu build (vite build genera la carpeta "dist")
